pref("extensions.fbmlconsole.locallogpath", 'C:\\Program Files\\MarkLogic\\Data\\Logs\\ErrorLog.txt');
pref("extensions.fbmlconsole.remotelogpath", 'http://localhost:8001/get-error-log.xqy?filename=ErrorLog.txt');
pref("extensions.fbmlconsole.remoteloguser", 'admin');
pref("extensions.fbmlconsole.remotelogpass", 'admin');
pref("extensions.fbmlconsole.logtype", 'local');
pref("extensions.fbmlconsole.customfiltertypes", '');
pref("extensions.fbmlconsole.togglestatus", '');
pref("extensions.fbmlconsole.togglebuttons", 'notice#warning#info');
pref("extensions.fbmlconsole.logConfigurations", "");
pref("extensions.fbmlconsole.selectedLogConfig", "default local log");